# This is a config for E2B sandbox template.
# You can use template ID (lpro3g4dq23fx68nyfkg) or template name (lovable-test-build) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lovable-test-build") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-test-build") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-test-build')

team_id = "da39489a-91de-459d-b314-e580a76aa5c5"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-test-build"
template_id = "lpro3g4dq23fx68nyfkg"
